apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 1
  storage:
    size: 20Gi
    storageClass: managed-csi
  bootstrap:
    initdb:
      database: keycloak
      owner: kcadmin
      secret:
        name: keycloak-db-secret
  monitoring:
    enablePodMonitor: true
