apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: kcadmin
      secret:
        name: keycloak-db-secret
