apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak

spec:
  interval: 5m

  chartRef:
    kind: OCIRepository
    name: keycloak
    namespace: flux-system

  values:
    replicas: 1

    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.3.0"

    admin:
      username: admin
      password: YOUR_KEYCLOAK_ADMIN_PASSWORD

    db:
      vendor: postgres
      host: keycloak-db-rw.keycloak.svc.cluster.local
      port: 5432
      database: keycloak
      username: kcadmin
      password: YOUR_DB_PASSWORD

    service:
      type: ClusterIP
